baseURL = "https://blog.delineate.io"
languageCode = "en-gb"
title = "delineate.io"
theme="delineateio-theme"
pygmentsstyle = "monokailight"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="light"
	useCDN=true

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/delineateio"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/@delineateio"

[[menu.main]]
name = "posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "about"
url = "/about"
weight = 4